// Code generated by protoc-gen-go. DO NOT EDIT.
// source: max.proto

/*
Package max is a generated protocol buffer package.

It is generated from these files:
	max.proto

It has these top-level messages:
	Request
	Response
*/
package max

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Num int32 `protobuf:"varint,1,opt,name=Num" json:"Num,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Response struct {
	Max int32 `protobuf:"varint,1,opt,name=Max" json:"Max,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "max.Request")
	proto.RegisterType((*Response)(nil), "max.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	FindMaxNumber(ctx context.Context, opts ...grpc.CallOption) (Service_FindMaxNumberClient, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) FindMaxNumber(ctx context.Context, opts ...grpc.CallOption) (Service_FindMaxNumberClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Service_serviceDesc.Streams[0], c.cc, "/max.Service/FindMaxNumber", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceFindMaxNumberClient{stream}
	return x, nil
}

type Service_FindMaxNumberClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type serviceFindMaxNumberClient struct {
	grpc.ClientStream
}

func (x *serviceFindMaxNumberClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceFindMaxNumberClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Service service

type ServiceServer interface {
	FindMaxNumber(Service_FindMaxNumberServer) error
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_FindMaxNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).FindMaxNumber(&serviceFindMaxNumberServer{stream})
}

type Service_FindMaxNumberServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type serviceFindMaxNumberServer struct {
	grpc.ServerStream
}

func (x *serviceFindMaxNumberServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceFindMaxNumberServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "max.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindMaxNumber",
			Handler:       _Service_FindMaxNumber_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "max.proto",
}

func init() { proto.RegisterFile("max.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4d, 0xac, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4d, 0xac, 0x50, 0x92, 0xe6, 0x62, 0x0f, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0xf6, 0x2b, 0xcd, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0d, 0x02, 0x31, 0x95, 0x64, 0xb8, 0x38, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x41, 0xb2, 0xbe, 0x89, 0x15, 0x30, 0x59, 0xdf, 0xc4, 0x0a, 0x23, 0x5b, 0x2e, 0xf6, 0xe0,
	0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x23, 0x2e, 0x5e, 0xb7, 0xcc, 0xbc, 0x14, 0xdf, 0xc4,
	0x0a, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x21, 0x1e, 0x3d, 0x90, 0x3d, 0x50, 0x93, 0xa5, 0x78,
	0xa1, 0x3c, 0x88, 0x51, 0x4a, 0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x49, 0x6c, 0x60, 0x57, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x13, 0x91, 0x8f, 0xa1, 0x92, 0x00, 0x00, 0x00,
}
